import sys


OS_WIN = 'windows'
OS_MAC = 'darwin'
OS_LINUX = "linux"

PLATFORM = sys.platform

SCREEN_TOP_MARGIN_MAC = 25
SCREEN_TOP_MARGIN_LINUX = 30
SCREEN_TOP_MARGIN_WINDOWS = 30

SCREEN_TOP_MARGIN = SCREEN_TOP_MARGIN_MAC if PLATFORM == OS_MAC else SCREEN_TOP_MARGIN_WINDOWS if PLATFORM == OS_WIN else SCREEN_TOP_MARGIN_LINUX
